apiVersion: apps/v1
kind: Deployment
metadata:
  name: anime-win-xp
  namespace: anime-win-xp
  labels:
    app: anime-win-xp
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: anime-win-xp
  template:
    metadata:
      labels:
        app: anime-win-xp
    spec:
      nodeSelector:
        role: voice
      containers:
        - name: web
          image: ghcr.io/nekwo/anime-win-xp:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
              name: http
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 30
